site_name:  Siddhi-IO-googlepubsub
site_description: Siddhi IO googlepubsub Extension
site_author: WSO2
site_url: https://wso2-extensions.github.io/siddhi-io-googlepubsub/
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
repo_name: Siddhi-io-googlepubsub
repo_url: https://github.com/wso2-extensions/siddhi-io-googlepubsub
copyright: Copyright &copy; 2011 - 2019 WSO2
theme:
  name: material
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
google_analytics:
  - UA-103065-28
  - auto
extra:
  social:
    - type: github
      link: https://github.com/wso2/siddhi
    - type: linkedin
      link: https://www.linkedin.com/groups/13553064
pages:
  - Welcome: index.md
  - API docs:
      - latest: api/latest.md
  - License: license.md
